name: Sync OpenAPI definition to readme.com

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install rdme cli
        run: npm install -g rdme

      - name: Upload openapi.yaml
        working-directory: docs
        run: rdme openapi upload openapi.yaml --key=${{ secrets.README_API_KEY }}
